### ISSUE TITLE
Access to Northern Ireland data

### ISSUE THREAD

**Issue by cfr95fr** [publichealthengland/coronavirus-dashboard-api-R-sdk#3]
Hello, thank you for putting online this great API.
I am using R4.0.2 on Windows 10.
When I try to access the Northern Ireland data using area name "northern ireland" or area code "N92000002", the retrieved content is empty.   It works well for the 3 other nations though.

**Comment by xenatisch** [comment]
Hi @cfr95fr 

I am assuming that you are talking about the deaths date. We didn't have them for NI in our database until today. It was just released and should be available (for deaths and some other metrics). We're working to release more localised data for some of the metrics - including deaths... keep an eye out.  

As a rule of thumb, if the data for a specific metric or at a specific level are not displayed on the website, chances are it is because we don't have it in our database. Our data and dev teams are working round the clock to include additional metrics and expand the existing ones. 

Hope this helps.

**Comment by cfr95fr** [comment]
Hello @xenatisch, thanks for the fix, it's working now ! - CF
